 NumPy Vectorised form of array

In [3]:
# create two dimension array aving 6 rows and 5 colmns 
#convert 1D array to multidim
import numpy as np
array = np.array(np.arange(1,31))
two_array = array.reshape(5,6) # create  any variable two prit functn 
print(two_array)
array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# slicing Que. i want to 7,8,9 and 2nd row 12,13,14
two_array[1:3,1:4]
# x is a row index, y is a column indx 

array([[ 7,  8,  9],
       [12, 13, 14]])

In [5]:
two_array[3: , 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [7]:
two_array[5: ,-1:] # -1 is called start last element 

array([[30]])

In [ ]:
# i want to only 30 and placed on 0 index 
# -1 is called start last element 
print(two_array[5:,-1:][0][0])

30


In [ ]:
# statistical function maths  function aggregate function 
a= np.array([20,30,49])
b= np.array([30,40,59])
print(a+b) # add all column vise  value
print(a*b)

[ 50  70 108]
[ 600 1200 2891]
