In [1]:
import numpy as np
#define list 
arr = [10,20,30]
#define numpy array : narr
narr = np.array(arr)
print(narr)

[10 20 30]


In [2]:
#check type of arr
print(type(narr))
print(narr.ndim)

<class 'numpy.ndarray'>
1


In [3]:
#create 2D array
arr = [[10,20,30],[40,50,60],[70,40,58]]
print(type(narr))
print(narr.ndim)
print(narr.shape)

<class 'numpy.ndarray'>
1
(3,)


In [10]:
''' 
number of elements presents in equal to array= 10
is reshape array convert to specific 5 rows and 2 columns (2,5)
padding = slicing image 
'''
array = np.array([0,1,2,3,4,5,6,7,8,9])
array.reshape(2,5)   # that is 5 rows 3 columns also used  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
array.min() , array.max() , array.sum()  # 0 axis is called x axis & 1 called y axis

(np.int64(0), np.int64(9), np.int64(45))

Most IMP topic Flattering 


In [ ]:
#create two dimensional array and use flatten 
#flatten(): converts multi dimensin array to 1D array use for image pro

In [13]:
#create two dimensional array and use flatten function most important
#flatten(): is function converts multi dimensin array to 1D array use for image process used in ml
array = np.array([[10,20],[30,40],[50,60]])
array.flatten()
# tolist() : function is convert numpy array to list 
lst=array.tolist()  
print(lst)
print(type(lst))

[[10, 20], [30, 40], [50, 60]]
<class 'list'>


In [ ]:
z = np.zeros((3,3)) #always written 2 brackets and float type 
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
o = np.ones((3,4)) # ALL matrics involve is 1 
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
e = np.eye(6) # square matrics means diagonal 1 same 
e

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# arrange() function: create automatic array using slicing tric (start,stop,step)
# same as create list 
array = np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
'''Ques. i want to arrange my array in 2 dimenstion 
reshape convert to 1D array to multiD
 flatten convert to MultiD to 1D'''
narray = array.reshape(1,5,4)
print(narray.ndim)
print(narray)

3
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]


In [29]:
narray.std()

np.float64(5.766281297335398)

In [30]:
narray.var() # variances 

np.float64(33.25)